name: Daily Social Media Posts

on:
  schedule:
    # Runs daily at 4:00 PM UK time (adjust for daylight saving)
    - cron: '0 16 * * *'  # UTC time
  workflow_dispatch:  # Allows manual triggering

jobs:
  post_content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Create credentials file
      env:
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      run: |
        echo "$YOUTUBE_CLIENT_SECRET" > credentials/client_secret.json
        
    - name: Run posting script
      env:
        YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        INSTAGRAM_USER_ID: ${{ secrets.INSTAGRAM_USER_ID }}
      run: python src/main.py
      
    - name: Commit schedule updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add content/schedule.json
        git diff --staged --quiet || git commit -m "Update posting schedule [skip ci]"
        git push